name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:fisica

    - name: SSH Archive
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: archive
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
            sudo bash -lc '
            set -e
            cd /var/www
            cd hugo/
            git pull
            hugo
            cd ..
            rm webpage/hugo/ -rf
            mkdir webpage/hugo/
            mv hugo/public/ webpage/hugo/
            '

    - name: Logout of Tailscale
      run: echo '${{ secrets.PASSWORD }}' | sudo -S tailscale logout
